### ISSUE TITLE
[Suggestion] Further Example of Best Practices

### ISSUE THREAD

**Issue by pfabri** [ltalirz/flask-sqlalchemy-circular-imports#1]
You might want to take a look at this on SE as well: [Avoiding Circular Imports in Flask with SQLAlchemy](https://stackoverflow.com/questions/42909816/can-i-avoid-circular-imports-in-flask-and-sqlalchemy/42910185#)

**Comment by ltalirz** [comment]
thanks!  in 650573fd975f315588b407fb24695e3cccc09907 I've adapted the boiler plate code a bit + added a link
